apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ts-sv
  name: nginx-ts-sv
  namespace: nginx-ts
spec:
  type: NodePort
  ports:
    - name: nginx-ts-sv-port
      port: 80
      nodePort: 30069
      targetPort: 80
  selector:
    app: nginx-ts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-ts
  name: nginx-ts
  namespace: nginx-ts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ts
  template:
    metadata:
      labels:
        app: nginx-ts
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: nginx-ts
          ports:
            - containerPort: 80